### PR TITLE
Adding cooler.fm podcast player user agent

### PR DESCRIPTION
**Pull request by smoothfm**

### CODE REVIEW

**Comment by johnspurlock** [comment]
Thanks - can you provide an example user-agent string?

**Comment by smoothfm** [comment]
> Thanks - can you provide an example user-agent string?

sure thing, 
`CoolerFM/1.0 iPhone/15 +https://cooler.fm`

thanks!

**Comment by johnspurlock** [comment]
Can you make sure you are setting your user-agent for streaming requests using AVPlayer?  It looks like you may be sending the default AppleCoreMedia ua right now.

PocketCasts has a good example of how to set this properly: https://github.com/Automattic/pocket-casts-ios/blob/trunk/podcasts/PlaybackItem.swift

**Comment by smoothfm** [comment]
> Can you make sure you are setting your user-agent for streaming requests using AVPlayer? It looks like you may be sending the default AppleCoreMedia ua right now.
> 
> PocketCasts has a good example of how to set this properly: https://github.com/Automattic/pocket-casts-ios/blob/trunk/podcasts/PlaybackItem.swift

can I ask where you are seeing that user agent come through? part of the reason why we made the PR in your repo is because our app is coming back "unknown" in a couple test podcasts we set up on captivate.fm + buzz sprout. and not sure if these services rely on some open source data like this one :)

when researching how to get user agent working, I did indeed come across pocket-casts and followed their example. for test purposes, hard coded:
`AVURLAssetHTTPUserAgentKey: "CoolerFM/1.0 iPhone/15 +https://cooler.fm",`

and passing this into our audio library (SwiftAudioEx) - appeared to be coming through when looking at headers via Requestly earlier today. I should note that this code is not on the current 1.0 production version of the app (coming in the next version once we are confident it's working)

**Comment by johnspurlock** [comment]
One easy way to check the raw user agent sent without setting up a proxy or anything is to enable wifi on the phone and use your app to play a podcast that uses the OP3 prefix (I typically use "Podnews Daily"), then hit the [OP3 api](https://op3.dev/api/docs) from a browser on a computer on the same wifi network to query for hits coming in for the current ip.

e.g. to see hits from your calling ip starting 12 hours ago: https://op3.dev/api/1/redirect-logs?start=-12h&format=json&token=preview07ce&hashedIpAddress=current

**Comment by smoothfm** [comment]
amazing - have verified that the user agent is correct in latest version. very cool service by the way!!
```
{
      "time": "2024-01-09T17:55:52.590Z",
      "uuid": "7c5abd19732742c78a8e04447081f395",
      "hashedIpAddress": "2ab0a3eda4e44b27de7c4da0d3966ab84c5bc1cb",
      "method": "GET",
      "url": "https://op3.dev/e,pg=9b024349-ccf0-5f69-a609-6b82873eab3c/podnews.net/audio/podnews231128.mp3?_from=Ruby?_from=cooler.fm",
      "userAgent": "CoolerFM/1.0 iPhone/15 +https://cooler.fm",
      "range": "bytes=33699-6336642",
      "xpsId": "4B892331-A33A-4CCE-A28D-33214A638AA9",
      "edgeColo": "ORD",
      "continent": "NA",
      "country": "US",
      "timezone": "America/Chicago",
      "regionCode": "IL",
      "region": "Illinois",
      "metroCode": "602"
}
```

so if one of the providers is reporting our app as "unknown" is that likely because our app just launched, not many streams/downloads, etc?

**Comment by johnspurlock** [comment]
Sounds good - yes if `unknown` that's because they haven't added you to whatever ua -> app rollup logic they are using.  None of them are open source, so it's kind of hard to tell - but several companies contribute to and share the lists in the opawg repos.

Btw, the most current version of player user agents is over here:  https://github.com/opawg/user-agents-v2

I added you yesterday over there.

**Comment by jamescridland** [comment]
@smoothfm 

`t/audio/podnews231128.mp3?_from=Ruby?_from=cooler.fm`

I suspect the useragent for your RSS feed grabber is "Ruby" (i.e. you haven't actually set it). It would be great if you could, please; [here's how to set it for that library](https://stackoverflow.com/questions/5798037/how-to-set-a-custom-user-agent-in-ruby).

(You have found a bug in my RSS generator, which is nice - you're adding the _from parameter yourself, and that should be overwriting whatever we set.)

**Comment by jamescridland** [comment]
...if you use https://podnews.net/podcast/i8xeg you can see your RSS useragent in, I think, season 2 episode 1 from memory.

**Pull request merged**
