### PR TITLE
Add Bitcast.fm to user agents list

### PR DESCRIPTION
**Pull request by mikek90**
This PR adds Bitcast.fm crawler jobs to user-agents list

### CODE REVIEW

**Comment by jamescridland** [comment]
Thank you!

**Comment by mikek90** [comment]
@jamescridland thank you for merging! For some reason I don't see `Bitcast` entry on master [rss-ua.json](https://github.com/opawg/podcast-rss-useragents/blob/master/src/rss-ua.json) file. I am afraid it was deleted by accident in this [commit](https://github.com/opawg/podcast-rss-useragents/commit/7f3fff9a828e1147bfc973be429adfd7abb478fd). Do you want me to create another PR to add `Bitcast` again?

**Comment by jamescridland** [comment]
Ah, my fault. I'll go fix.

**Comment by mikek90** [comment]
Amazing, thank you @jamescridland! 🙏

**Pull request merged**
